# Generated by Django 5.2.8 on 2025-11-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('colour', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('price', models.IntegerField()),
                ('Product_code', models.IntegerField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=50)),
                ('Quality', models.CharField(max_length=20)),
            ],
        ),
    ]
